### ISSUE TITLE
Unable to Deploy using this buildpack

### ISSUE THREAD

**Issue by phereford** [HashNuke/heroku-buildpack-elixir#167]
Howdy @HashNuke !

Thank you so much for this wonderful buildpack. It has saved me countless of hours when having to deal with Heroku.

Today I hit an issue and was unable to deploy my phoenix/elixir application:
The error message returned from heroku is:
`remote: /app/.platform_tools/elixir/bin/elixir: 228: exec: erl: not found`

My best guess as to when this regression was introduced:
https://github.com/HashNuke/heroku-buildpack-elixir/commit/cf15a25546d78768f8cc57be7dc87ec08956612e#diff-84d19908b6dfdc8bd9f954602a764ef1R35-R39

My guess is due to having been able to successfully deploy my application all day yesterday but unable to deploy it within the past few minutes.

I know you are probably super busy, so if I am able to squirrel away some time, I can also dive into this issue. Thanks!

**Comment by john-griffin** [comment]
Just hit this also

**Comment by craiglyons** [comment]
Us as well. We switched to using a pin of this commit as our buildpack, which is working: https://github.com/HashNuke/heroku-buildpack-elixir.git#cd658c0b668dfcc2fd328fdaea45a41031b18305

Since there's no good way to announce these changes, it might be best to keep `master` stable and let people opt in for the `edge` releases, since using `master` is probably the more common pattern for using an external buildpack. 

Our team would be happy to help test edge releases in non-production environments.

**Comment by jesseshieh** [comment]
@craiglyons I'd be happy to merge a PR to introduce the edge pattern. That would be very much appreciated! 

I reverted the pull request that I believe caused this regression (https://github.com/HashNuke/heroku-buildpack-elixir/pull/168). Can anyone verify that the problem is fixed?

I didn't run into this error during my own tests. If anyone has reproduction steps on an example repo, that would really help.

**Comment by jc00ke** [comment]
It is fixed. I'm surprised that broke everything.

**Comment by amiel** [comment]
I ran in to this issue this morning as well. It is also fixed for me now. Thanks for the quick turnaround on fixing this @jesseshieh
