### ISSUE TITLE
Error building with Heroku-20 stack

### ISSUE THREAD

**Issue by jhg** [HashNuke/heroku-buildpack-elixir#190]
Will this repo be deprecated and users must migrate to https://github.com/elixir-buildpack in future? https://github.com/HashNuke/heroku-buildpack-elixir/pull/180

Currently I have same error than in https://github.com/HashNuke/heroku-buildpack-elixir/issues/179 but the fork also fails and there is not way to create an issue in the forked repo.

**Comment by KazW** [comment]
Hey @jhg, sorry about this, I've enabled issues in the elixir-buildpack repo (forks have them disabled by default). I took a break working on this during the holidays, but I have some changes in mind to address this issue and a few others.

**Comment by KazW** [comment]
This issue can probably be closed now, I've updated the elixir-buildpack fork to address the issues. I wrote a more detailed response in #179.

**Comment by axelson** [comment]
Unless the error was actually fix in this repo, then shouldn't either #190 or #179 remain open? Additionally I think it should be pinned.

**Comment by KazW** [comment]
@axelson That's what makes it a bit complicated, the problem isn't really in this repo, it's just visible here. The issue is that the [build system](https://github.com/HashNuke/heroku-buildpack-elixir-otp-builds) compiles OTP using Cedar 14.

The solution to the error is to compile OTP using the appropriate stack version. The only change that would need to be made to this buildpack is using a new URL that was specific for the stack.

**Comment by jesseshieh** [comment]
@jhg There is a PR now to support heroku-20 here: #191
