### ISSUE TITLE
Find alternative place for hosting OTP releases

### ISSUE THREAD

**Issue by ericmj** [HashNuke/heroku-buildpack-elixir#56]
Currently Hex is hosting them, but Hex has enough costs hosting it's own stuff. Additionally I spend enough on other administrative tasks related to Hex (it takes some of time to build the releases and making sure they are up to date). It's not sustainable long term for Hex to continuing the hosting. If anyone wants to take it over I will walk them through the process of building.

**Comment by ericmj** [comment]
Currently 37 releases are hosted (17.0-18.1.3), taking up 2.25gb space where each release is ~60mb.

**Comment by HashNuke** [comment]
@ericmj Tweeting this out to check if anyone would sponsor these.

**Comment by mtwilliams** [comment]
Have [this](https://gist.github.com/mtwilliams/3d0113fc6644388f9b59#file-otp-release-tracker-rb-L34) script running on a Droplet, kindly provided by dikaio (as well as S3! :+1:). Going to clean-up a few things and put it in CRON. Solves that, I guess.

**Comment by HashNuke** [comment]
@mtwilliams please hold off on this.

The plan is to have a list of versions in a text file in this repo. When a new version is released, anyone can send a PR and have a build up and running for that version. This eliminates the need for a droplet and a cron. Travis or CircleCI can take care of the builds.

I'll also most likely host this on my own S3 account since the expenses are very low.

**Comment by mtwilliams** [comment]
It's also more easily audited as well.

Is your intent to build only when the pull-request is merged?

**Comment by HashNuke** [comment]
Build when PR is sent to verify a version exists. Then build and push to S3
only when merged into master.
That automates verifying the version.

**Comment by HashNuke** [comment]
Done. So closing issue :)
